found/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT
    }),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('web.home.urls', namespace='home')),
    url(r'^news/', include('web.news.urls', namespace='news')),
    url(r'^projects/', include('web.projects.urls', namespace='projects')),
    url(r'^partners/', include('web.partners.urls', namespace='partners')),
    url(r'^reports/', include('web.reports.urls', namespace='reports')),
    url(r'^mediafiles/', include('web.media.urls', namespace='mediafiles')),
    url(r'^faq/', include('web.faq.urls', namespace='faq'))
]

found/found/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('web.home.urls', namespace='home')),
    url(r'^news/', include('web.news.urls', namespace='news'))
]

found/web/home/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='index'),
    url(r'^contacts/$', views.ContactsView.as_view(), name='contacts'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
]

found/web/news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.NewsListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.NewsDetailView.as_view(), name='detail')
]

found/web/urls.py
from django.conf import url

from . import views

urlpatterns = [
    url('^$', views.FaqView.as_view(), name='view')
]

found/templates/partials/footer.html
<div class="footer">
  <div class="footer-menu">
    
  </div>
</div>

found/templates/partials/header.html
<div class="header">
  pass
</div>

found/templates/partials/menu.html
<div class="menu-open">&#9776;</div>
<div class="menu">
  <div class="menu-title">
    <div class="close">&times;</div>
  </div>
  {% include 'partials/menu_list.html' %}
</div>

found/templates/partials/menu_list.html
<ul>
  <li>
    <a href="{% url 'home:index' %}">Home</a>
  </li>
  <li>
    <a href="{% url 'news:list' %}">News</a>
  </li>
  <li>
    <a href="{% url 'mediafiles:view' %}">Media</a>
  </li>
  <li>
    <a href="{% url 'home:about' %}">About</a>
  </li>
  <li>
    <a href="{% url 'reports:list' %}">Reports</a>
  </li>
  <li>
    <a href="{% url 'projects:list' %}">Projects</a>
  </li>
  <li>
    <a href="{% url 'home:contacts' %}">Contacts</a>
  </li>
  <li>
    <a href="{% url 'partners:list' %}">Partners</a>
  </li>
</ul>

found/templates/partials/scripts.html
{% load static %}

<script src="{% static 'js/libs/jquery/dist/jquery.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/script.js' %}" charset="utf-8"></script>

found/templates/partials/search_bar.html
<div class="search">
  <div class="search-icon">
    <span class="search-icon-text">&#9906;</span>
  </div>
  <div class="search-input">
    <input type="text" name="name" placeholder="Search" value="" />
  </div>
</div>

found/templates/partials/styles.html
{% load static %}
<link rel="stylesheet" href="{% static 'js/libs/skeleton/css/normalize.css' %}" />
<link rel="stylesheet" href="{% static 'js/libs/skeleton/css/skeleton.css' %}" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" />