found/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT
    }),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('web.home.urls', namespace='home')),
    url(r'^news/', include('web.news.urls', namespace='news')),
    url(r'^projects/', include('web.projects.urls', namespace='projects')),
    url(r'^partners/', include('web.partners.urls', namespace='partners')),
    url(r'^reports/', include('web.reports.urls', namespace='reports')),
    url(r'^mediafiles/', include('web.media.urls', namespace='mediafiles')),
    url(r'^faq/', include('web.faq.urls', namespace='faq'))
]

found/found/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('web.home.urls', namespace='home')),
    url(r'^news/', include('web.news.urls', namespace='news'))
]

found/web/news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.NewsListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.NewsDetailView.as_view(), name='detail')
]

found/web/urls.py
from django.conf import url

from . import views

urlpatterns = [
    url('^$', views.FaqView.as_view(), name='view')
]

found/web/news/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext as _

from web.projects.models import Project


class Entry(models.Model):
    main_image = models.ImageField(
        _('main image'),
        null=True,
        upload_to=settings.NEWS_UPLOAD_FOLDER
    )
    project = models.ForeignKey(Project, related_name='entries',
        verbose_name=_('project'), null=True, blank=True)
    title = models.CharField(_('title'), max_length=255, unique=True)
    body = models.TextField(_('body'))
    is_recomended = models.BooleanField(_('is recomended'), default=False)
    is_anouns = models.BooleanField(_('is anouns'), default=False)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    updated = models.DateTimeField(_('updated'), auto_now=True)

    class Meta:
        verbose_name_plural = _('entries')

    def __str__(self):
        return '{}: {}'.format(_('news entry'), self.title)

    @property
    def slug(self):
        return '-'.join(self.title.split(' '))

    def main_admin_image(self):
        return '<img src="{}" width="100" height="100">'.format(
            self.main_image.url
        )
    main_admin_image.allow_tags = True

found/web/news/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Entry


class NewsListView(ListView):
    model = Entry
    template_name = 'news/list.html'


class NewsDetailView(DetailView):
    model = Entry
    context_object_name = 'entry'
    template_name = 'news/detail.html'

found/web/news/templates/news/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="content-block news-background" style="background: url({{ entry.main_image.url }})">
  <div class="detail-block-text">
    <h1>{{ entry.title | title }}</h1>
  </div>
</div>
<div class="content-block">
  <div class="content-block detail-content-block">
    <div class="content">
      {{ entry.body | safe }}
    </div>
  </div>
</div>
{% endblock content %}

found/web/news/templates/news/list.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
<div class="content-block">
  <div class="block-header news-content-header">
    <h2>Новини</h2>
  </div>
  <div class="content">
    <div class="list-block">
      {% for entry in object_list %}
        <div class="entry-item">
          <div class="entry-item-image">
            <img src="{{ entry.main_image.url }}" width="330" height="300" alt="entry image" />
          </div>
          <div class="entry-item-title">
            <a href="{% url 'news:detail' entry.pk %}">{{ entry.title }}</a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}